version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    # We copy some external foders/file needed within the docs folder
    pre_build:
      - cp -r tutorials docs/source/tutorials

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py

formats: all

# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
