name: pyissm
channels:
  - accessnri
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.9
  - xarray
  - numpy
  - scipy
  - netcdf4
  - pandas
  - matplotlib
  - attrs
  - pyyaml

  # Jupyter kernel support
  - ipykernel

  # Common packaging/install tooling
  - pip>=21.3
  - setuptools>=61.0
  - wheel
